version: '3'

services:
  web:
    build: .
    volumes:
      - frontend:/usr/app/
    ports:
      - "4100:4100"
    volumes:
      - korekbackend_ssl_cetificate:/etc/letsencrypt/:ro

volumes:
  frontend: {}
  korekbackend_ssl_cetificate:
    external: true