version: '3'

services:

  web:
    build: ./frontend
    tty: true
    volumes:
      - frontend:/usr/app/
      - korekfrontend_ssl_cetificate:/etc/letsencrypt/:ro
    ports:
      - "4100:4100"
      #- "443:4100"

  nginx_react:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - korekfrontend_ssl_cetificate:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

volumes:
  frontend: {}
  korekfrontend_ssl_cetificate: {}

  #korekfrontend_ssl_cetificate:
    #external: true
