version: '3'

services:
  web:
    build: .
    volumes:
      - frontend:/usr/app/
      - korekbackend_ssl_cetificate:/etc/letsencrypt/:ro
    ports:
      - "443:4100"

volumes:
  frontend: {}
  korekbackend_ssl_cetificate:
    external: true